#!/bin/sh

HOSTNAME=`echo $@ | sed s/.*@//`

set_bg () {
  osascript -e "tell application \"Terminal\" to set background color of window 1 to $1"
}

on_exit () {
  set_bg "{0, 0, 0, 50000}"
}
trap on_exit EXIT

case $HOSTNAME in
  stage|stage-origin) set_bg "{0, 6000, 3000, 10000}" ;;
  production|finder-1) set_bg "{6000, 3000, 0, 50000}" ;;
  *) set_bg "{3000, 0, 6000, 50000}" ;;
esac

/usr/bin/ssh "$@"