#!/bin/sh

# Download, compile, and copy the vcprompt command to ~/bin.
# Originally from Geoffrey Grosenbach

mkdir -p ~/tmpvcprompt
cd ~/tmpvcprompt
hg clone http://vc.gerg.ca/hg/vcprompt/
cd vcprompt
make
cp vcprompt ~/bin/vcprompt
rm -rf ~/tmpvcprompt