#!/bin/sh

# Download, compile, and copy the vcprompt command to ~/bin.
# Originally from https://github.com/djl/vcprompt

curl -sL https://github.com/djl/vcprompt/raw/master/bin/vcprompt > ~/bin/vcprompt
chmod 755 ~/bin/vcprompt
source ~/.bashrc
