#!/bin/sh

# Download, compile, and copy the vcprompt command to ~/bin.
# Originally from Geoffrey Grosenbach

mkdir -p ~/tmpvcprompt
cd ~/tmpvcprompt
curl http://vc.gerg.ca/hg/vcprompt/archive/tip.zip > tip.zip
unzip tip.zip
cd `ls|grep vcprompt`
make
cp vcprompt ~/bin/vcprompt
rm -rf ~/tmpvcprompt
cd
source ~/.bashrc